// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhGvWw-j1g8pSifd4xrnZ6q6gNdhCE1KE',
    appId: '1:802383386477:web:d74a74b83b0a8d94d02c64',
    messagingSenderId: '802383386477',
    projectId: 'finanzafamiliar-3ac83',
    authDomain: 'finanzafamiliar-3ac83.firebaseapp.com',
    storageBucket: 'finanzafamiliar-3ac83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu0xm4fGG4AXpR9fwgnzV3Lpkv1zIJrgk',
    appId: '1:802383386477:android:b181d3314d122078d02c64',
    messagingSenderId: '802383386477',
    projectId: 'finanzafamiliar-3ac83',
    storageBucket: 'finanzafamiliar-3ac83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAApKumtRpQrp0pDTXqlGltUELw34cVmoA',
    appId: '1:802383386477:ios:41e5d18ee58d2529d02c64',
    messagingSenderId: '802383386477',
    projectId: 'finanzafamiliar-3ac83',
    storageBucket: 'finanzafamiliar-3ac83.appspot.com',
    iosClientId: '802383386477-3itrkp5c4etftmc3e723ml1bvbm6jstf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ejemplo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAApKumtRpQrp0pDTXqlGltUELw34cVmoA',
    appId: '1:802383386477:ios:41e5d18ee58d2529d02c64',
    messagingSenderId: '802383386477',
    projectId: 'finanzafamiliar-3ac83',
    storageBucket: 'finanzafamiliar-3ac83.appspot.com',
    iosClientId: '802383386477-3itrkp5c4etftmc3e723ml1bvbm6jstf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ejemplo1',
  );
}
